blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question or discuss an idea
    url: https://discord.gg/casperblockchain
    about: Ask your questions and discuss your ideas in the `#smart-contracts` channel
